version: '3.8'

services:
  postgres-pagamento:
    image: postgres:latest
    container_name: postgres-pagamento
    environment:
      POSTGRES_DB: pagamentodb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rede-pagamento

  pagamento-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagamento-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres-pagamento
      DB_PORT: 5432
      DB_NAME: pagamentodb
      DB_USER: usuario
      DB_PASSWORD: senha
    depends_on:
      - postgres-pagamento
    networks:
      - rede-pagamento

networks:
  rede-pagamento:
    driver: bridge

volumes:
  postgres-data:
